module Elm.Parser.ElmVerifyExampleTest exposing (suite)

import Elm.Parser
import Expect
import Test exposing (Test, describe, test)


suite : Test
suite =
    describe "Test fragments generated by elm-verify-example"
        [ test "Test negatives"
            (\_ ->
                negatives
                    |> Elm.Parser.parseToFile
                    |> Expect.ok
            )
        ]


negatives : String
negatives =
    """module Foo exposing (..)

a = [ (-1,-1), (-1,0), (-1,1)
    , (0,-1), (0,0), (0,1)
    , (0,2), (1,-1), (1,0)
    , (1,1), (1,2), (2,0)
    , (2,1), (2,2)
    ]
"""
